# Generated by Django 3.0.8 on 2020-09-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200902_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
